import type { Language } from './types';

const uiText = {
  en: {
    title: 'AI Recipe Generator',
    ingredientInputPlaceholder: 'Enter an ingredient (e.g., chicken, potatoes)',
    addIngredientButton: 'Add',
    generateRecipeButton: 'Generate Recipe',
    generatingRecipeButton: 'Generating...',
    recipeTitle: 'Your Culinary Creation',
    errorGenerating: 'Oops! Something went wrong while generating the recipe. Please try again.',
    prepTime: 'Prep Time',
    cookTime: 'Cook Time',
    calories: 'Calories',
    ingredients: 'Ingredients',
    instructions: 'Instructions',
    timeConstraint: 'Max time (in minutes)',
    downloadPdf: 'Download PDF',
    share: 'Share',
    shareError: 'Error sharing recipe.',
    pdfError: 'Error generating PDF.',
    ingredientHelperText: 'Enter ingredients, separated by commas or new lines.',
    initialIngredients: 'chicken breast, potatoes, carrots',
    recipeCopied: 'Recipe copied to clipboard!',
    loadingPhrases: [
      'Whisking up ideas...',
      'Simmering the perfect plan...',
      'Sourcing the freshest concepts...',
      'Preheating the AI oven...',
      'Slicing and dicing data...',
    ],
  },
  ru: {
    title: 'AI Генератор Рецептов',
    ingredientInputPlaceholder: 'Введите ингредиент (например, курица, картофель)',
    addIngredientButton: 'Добавить',
    generateRecipeButton: 'Создать Рецепт',
    generatingRecipeButton: 'Создание...',
    recipeTitle: 'Ваше Кулинарное Творение',
    errorGenerating: 'Ой! Что-то пошло не так при создании рецепта. Пожалуйста, попробуйте еще раз.',
    prepTime: 'Время подг.',
    cookTime: 'Время гот.',
    calories: 'Калории',
    ingredients: 'Ингредиенты',
    instructions: 'Инструкции',
    timeConstraint: 'Макс. время (в минутах)',
    downloadPdf: 'Скачать PDF',
    share: 'Поделиться',
    shareError: 'Ошибка при отправке рецепта.',
    pdfError: 'Ошибка при создании PDF.',
    ingredientHelperText: 'Введите ингредиенты, разделяя их запятыми или новыми строками.',
    initialIngredients: 'куриная грудка, картофель, морковь',
    recipeCopied: 'Рецепт скопирован в буфер обмена!',
    loadingPhrases: [
      'Взбиваем идеи...',
      'Подбираем специи...',
      'Нарезаем лучшие ингредиенты...',
      'Разогреваем AI-духовку...',
      'Анализируем ваши продукты...',
    ],
  },
};

export const getUiText = (lang: Language) => uiText[lang];